import type { ChatV2Detail, ChatV2Message, ChatV2Page, ChatV2Record, ChatV2StreamEvent, CreateChatV2MessageRequest, CreateChatV2Request, UpdateChatV2Request } from '@acongm/kb-types';
import { ChatStreamError, parseSseStream } from './chat-stream';

export const DEFAULT_CHATS_PROXY = '/api/chats';
export type ChatV2RequestOptions = { baseUrl?: string; accessToken?: string; signal?: AbortSignal };
type RawChat = { id:string; user_id:string; title:string|null; page_path:string|null; module_key:string|null; metadata:Record<string,unknown>|null; created_at:string; updated_at:string };
type RawMessage = { id:string; chat_id:string; user_id:string; client_message_id:string|null; parent_message_id:string|null; role:ChatV2Message['role']; parts:ChatV2Message['parts']; metadata:Record<string,unknown>|null; created_at:string };
const base=(v?:string)=>(v||'').trim()||DEFAULT_CHATS_PROXY;
const headers=(token?:string,extra:Record<string,string>={})=>({'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{ }),...extra});
async function body(r:Response){try{return (r.headers.get('content-type')||'').includes('application/json')?await r.json():{message:await r.text()}}catch{return undefined}}
async function json<T>(r:Response):Promise<T>{if(!r.ok){const b=await body(r);const x=(b&&typeof b==='object'?b:{}) as Record<string,unknown>;throw new ChatStreamError(typeof x.message==='string'?x.message:`Chat 请求失败 (${r.status})`,{status:r.status,code:typeof x.code==='string'?x.code:undefined,body:b})}return await r.json() as T}
const chat=(r:RawChat):ChatV2Record=>({id:r.id,userId:r.user_id,title:r.title||undefined,pagePath:r.page_path||undefined,moduleKey:r.module_key||undefined,metadata:r.metadata||{},createdAt:r.created_at,updatedAt:r.updated_at});
const msg=(r:RawMessage):ChatV2Message=>({id:r.id,chatId:r.chat_id,userId:r.user_id,clientMessageId:r.client_message_id||undefined,parentMessageId:r.parent_message_id||undefined,role:r.role,parts:Array.isArray(r.parts)?r.parts:[],metadata:r.metadata||{},createdAt:r.created_at});
export async function createChatV2(input:CreateChatV2Request={},o:ChatV2RequestOptions={}):Promise<ChatV2Record>{return chat(await json<RawChat>(await fetch(base(o.baseUrl),{method:'POST',headers:headers(o.accessToken),body:JSON.stringify(input),signal:o.signal})))}
export async function getChatV2(id:string,o:ChatV2RequestOptions={}):Promise<ChatV2Detail>{const r=await json<{chat:RawChat;messages?:RawMessage[];nextCursor?:string|null}>(await fetch(`${base(o.baseUrl)}/${encodeURIComponent(id)}`,{headers:headers(o.accessToken),signal:o.signal}));return{chat:chat(r.chat),messages:(r.messages||[]).map(msg),nextCursor:r.nextCursor||undefined}}
export async function streamChatMessageV2(id:string,input:CreateChatV2MessageRequest,o:ChatV2RequestOptions={}):Promise<AsyncGenerator<ChatV2StreamEvent>>{const r=await fetch(`${base(o.baseUrl)}/${encodeURIComponent(id)}/messages/stream`,{method:'POST',headers:headers(o.accessToken,{Accept:'text/event-stream'}),body:JSON.stringify(input),signal:o.signal});if(!r.ok||!r.body){const b=await body(r);const x=(b&&typeof b==='object'?b:{}) as Record<string,unknown>;throw new ChatStreamError(typeof x.message==='string'?x.message:`Chat 请求失败 (${r.status})`,{status:r.status,code:typeof x.code==='string'?x.code:undefined,body:b})}return parseSseStream<ChatV2StreamEvent>(r.body)}
export async function listChatsV2(page:{limit?:number;after?:string}={},o:ChatV2RequestOptions={}):Promise<ChatV2Page<ChatV2Record>>{const p=new URLSearchParams();if(page.limit)p.set('limit',String(page.limit));if(page.after)p.set('after',page.after);const r=await json<{chats?:RawChat[];nextCursor?:string|null}>(await fetch(`${base(o.baseUrl)}${p.size?`?${p}`:''}`,{headers:headers(o.accessToken),signal:o.signal}));return{items:(r.chats||[]).map(chat),nextCursor:r.nextCursor||undefined}}
export async function updateChatV2(id:string,patch:UpdateChatV2Request,o:ChatV2RequestOptions={}):Promise<ChatV2Record>{return chat(await json<RawChat>(await fetch(`${base(o.baseUrl)}/${encodeURIComponent(id)}`,{method:'PATCH',headers:headers(o.accessToken),body:JSON.stringify(patch),signal:o.signal})))}
